NODE_VERSION = "20"
  PRISMA_GENERATE_DATAPROXY = "true"
  PRISMA_GENERATE_SKIP_DOWNLOAD = "true"
=======
[build.environment]
  NODE_VERSION = "20.0.0"
  PRISMA_GENERATE_DATAPROXY = "true"
  PRISMA_GENERATE_SKIP_DOWNLOAD = "true"
